---
title: "Lab 8"
author: "Claudius Taylor, Tom Wilson, Junpu Zhao"
date: "10/24/2018"
output: pdf_document
---

```{R}
library(astsa)
```
Let 
$x_t = 0.6x_{t-1} - 0.7x_{t-2} + w_t + w_{t-1} + 0.2w_{t-2}$

equivalently 

$x_1 - 0.6 x_{t-1} + 0.7 x_{t-2} = w_t + w_{t-1} + 0.2w_{t-2}$

$x_1(1 - 0.6 B + 0.7 B^2) = w_t(1 + B + 0.2B^2)$

$x_t \phi(z) = w_t \theta(z)$

with

$\phi(z) = 1 - 0.6 B + 0.7 B^2$ 

and

$\theta(z) = 1 + B + 0.2B^2$


```{R}
phi_z   = c(1, -0.6, 0.7)
theta_z = c(1,    1, 0.2)
```

```{R}
roots_of_phi = polyroot(phi_z)
roots_of_phi

roots_of_theta = polyroot(theta_z)
roots_of_theta
```

$\phi(z)$ has roots at $B = 0.428571 \pm 1.11575 i$

$\theta(z)$ has roots at $B=-3.618$ and $B=-1.38197$

$\phi(z)$ and $\theta(z)$ do not share any roots therefore this model of $x_t$ is an ARMA(2,2) model.

# i. Determine if it is invertible or stationary/causal.

an ARMA process is invertible only when the roots of $\theta(z)$ lie outside the unit circle.

```{R}
Mod(roots_of_theta)
```

This model of $x_t$ is invertible.

an ARMA process is stationary/causal only when the roots of $\phi(z)$ lie outside the unit circle

```{R}
Mod(roots_of_phi)
```

This model of $x_t$ is stationary/causal.

# ii. Generate a sample path using n = 100 observations, and produce the sample ACF and sample PACF

```{R}
arma22.sim <- arima.sim(list(order = c(2,0,2), ar = c(0.6, -0.7), ma = c(1, 0.2)), n = 100)
ts.plot(arma22.sim,
        ylab="", main=(expression(ARMA(2,2)~~~phi==+c(0.6, -0.7) ~~theta==+c(1, 0.2))))
acf(arma22.sim)
pacf(arma22.sim)
```



# iii. Produce the true ACF and the true PACF and compare with the sample ACF and sample PACF, respectively.

```{R}
y = ARMAacf(ar = c(0.6, -0.7),  ma = c(1, 0.2), lag.max = 20)
y = y[2:21]
plot(y, x = 1:20, type = "h", ylim = c(-1,1), xlab = "Lag",
      ylab = "ACF", main = "True ACF")
abline(h = 0)

acf(arma22.sim, main = "Sample ACF")

y = ARMAacf(ar = c(0.6, -0.7),  ma = c(1, 0.2), lag.max = 20, pacf=TRUE)
y = y[2:21]
plot(y, x = 1:20, type = "h", ylim = c(-1,1), xlab = "Lag",
      ylab = "True PACF", main = "True PACF")
abline(h = 0)

pacf(arma22.sim, main = "Sample PACF")
```

The true acf and sample acf both decay and oscillate in pairs
The true pacf and sample pacf both decay and strictly alternate sign.